"""
Audit Trail workbook (.xlsx) — the full, structured export of every
audited action in the workspace.

One workbook, two sheets:
  - Cover        — company, who generated it, when, range, event count
  - Audit Trail  — chronological table: # / Date / Time / User / Module /
                   Activity / Action code / Entity. Frozen header +
                   autofilter so it behaves like a workpaper, not a dump.

Timestamps are stored in UTC; the caller passes the browser's
`getTimezoneOffset()` so Date/Time columns render in the USER'S local
time, with the offset spelled out on the cover and in the column head —
an audit file where "when" is ambiguous is worse than none.

Styling comes from modules/exports/xlsx_builder.py (shared monochrome
CPA-workpaper look used by every other Nordavix export).
"""
from __future__ import annotations

from datetime import datetime, timedelta
from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from modules.exports.xlsx_builder import (
    MUTED,
    freeze_header,
    register_styles,
    set_column_widths,
    write_row,
    write_table_header,
)

# Map action prefixes (the part before the first ".") to the module name a
# CPA would recognize. Unknown prefixes fall back to a title-cased prefix so
# new modules never produce blank cells.
_MODULE_LABELS: dict[str, str] = {
    "recon":         "Reconciliations",
    "flux":          "Flux Analysis",
    "schedule":      "Schedules",
    "adjustment":    "Adjustments",
    "intercompany":  "Intercompany",
    "task":          "Tasks",
    "workspace":     "Workspace",
    "comment":       "Discussion",
    "trial_balance": "Flux Analysis",
    "qbo":           "Connections",
    "books":         "Books Setup",
    "tenant":        "Workspace",
}

_ENTITY_LABELS: dict[str, str] = {
    "trial_balance":      "Flux analysis",
    "variance":           "Variance",
    "account":            "Account",
    "reconciliation":     "Reconciliation",
    "schedule_item":      "Schedule item",
    "schedule_snapshot":  "Schedule snapshot",
    "proposed_entry":     "Proposed entry",
    "ic_pair":            "Intercompany pair",
    "ic_mark":            "Intercompany mark",
    "task":               "Task",
    "comment":            "Comment",
    "evidence":           "Evidence file",
    "bank_statement":     "Bank statement",
    "period":             "Period",
    "workspace":          "Workspace",
    "invitation":         "Invitation",
    "member":             "Member",
}


def module_for_action(action: str) -> str:
    prefix = (action or "").split(".", 1)[0]
    return _MODULE_LABELS.get(prefix, prefix.replace("_", " ").title() or "—")


def _entity_label(entity_type: str | None) -> str:
    if not entity_type:
        return ""
    return _ENTITY_LABELS.get(entity_type, entity_type.replace("_", " ").capitalize())


def _offset_label(tz_offset: int) -> str:
    """JS getTimezoneOffset() → 'UTC−05:00' style label.
    JS reports minutes UTC is AHEAD of local (EST = +300, IST = -330)."""
    total = -tz_offset  # minutes local is ahead of UTC
    sign = "+" if total >= 0 else "-"
    h, m = divmod(abs(total), 60)
    return f"UTC{sign}{h:02d}:{m:02d}"


def build_audit_workbook(
    *,
    company_name: str,
    generated_by: str,
    entries: list[dict[str, Any]],
    tz_offset: int = 0,
    range_label: str = "Full history",
) -> bytes:
    """entries: chronological-ASC dicts with keys
    created_at (aware datetime, UTC), action, entity_type, summary, user_name.
    """
    wb = Workbook()
    register_styles(wb)
    tz_label = _offset_label(tz_offset)
    now_local = datetime.utcnow() - timedelta(minutes=tz_offset)

    # ── Cover ────────────────────────────────────────────────────────────
    ws = wb.active
    ws.title = "Cover"
    ws.sheet_view.showGridLines = False
    set_column_widths(ws, [3, 26, 60])
    ws["B2"] = "Audit Trail"
    ws["B2"].style = "nx_h1"
    ws["B3"] = "Every recorded action in this workspace — who did what, and exactly when."
    ws["B3"].font = Font(name="Calibri", size=11, italic=True, color=MUTED)

    fields = [
        ("Company",      company_name),
        ("Generated by", generated_by),
        ("Generated at", f"{now_local.strftime('%m-%d-%Y %H:%M:%S')} ({tz_label})"),
        ("Range",        range_label),
        ("Events",       f"{len(entries):,}"),
        ("Timezone",     f"All Date/Time values shown in {tz_label}"),
    ]
    r = 5
    for label, value in fields:
        ws.cell(row=r, column=2, value=label).style = "nx_label"
        ws.cell(row=r, column=3, value=value).style = "nx_value"
        r += 1

    # ── Audit Trail ──────────────────────────────────────────────────────
    ws = wb.create_sheet("Audit Trail")
    ws.sheet_view.showGridLines = False
    headers = ["#", "Date", f"Time ({tz_label})", "User", "Module", "Activity", "Action code", "Entity"]
    widths  = [6, 12, 12, 24, 16, 78, 26, 18]
    set_column_widths(ws, widths)
    start = 4
    ws["A1"] = f"Audit Trail — {company_name}"
    ws["A1"].style = "nx_h2"
    ws["A2"] = f"{range_label} · {len(entries):,} events · times in {tz_label}"
    ws["A2"].font = Font(name="Calibri", size=10, italic=True, color=MUTED)
    write_table_header(ws, start, headers)
    freeze_header(ws, start)

    row = start + 1
    for i, e in enumerate(entries, start=1):
        created: datetime | None = e.get("created_at")
        if isinstance(created, datetime):
            local = created.replace(tzinfo=None) - timedelta(minutes=tz_offset)
            d_str, t_str = local.strftime("%m-%d-%Y"), local.strftime("%H:%M:%S")
        else:
            d_str, t_str = "", ""
        write_row(ws, row, [
            (i,                                   "nx_cell_int"),
            (d_str,                               "nx_cell_text"),
            (t_str,                               "nx_cell_text"),
            (e.get("user_name") or "System / AI", "nx_cell_text"),
            (module_for_action(e.get("action") or ""), "nx_cell_text"),
            (e.get("summary") or e.get("action") or "", "nx_cell_text"),
            (e.get("action") or "",               "nx_cell_muted"),
            (_entity_label(e.get("entity_type")), "nx_cell_text"),
        ])
        row += 1

    # Autofilter over the whole table so the file is sliceable by user /
    # module / date out of the box.
    last_col = get_column_letter(len(headers))
    ws.auto_filter.ref = f"A{start}:{last_col}{max(row - 1, start)}"

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
